### PR TITLE
Initial array prefixing implementation

### PR DESCRIPTION
**Pull request by rtsao**
Here's my first pass at fixing https://github.com/rofrischmann/inline-style-prefix-all/issues/13

One question: Is it intentional that this module mutates the original style object? I think an immutable API might be easier to reason about (e.g. debugging, etc.). I've implemented this feature in an immutable fashion, though I might be able to make this a bit simpler by using mutation. I suppose performance could be better with an API that mutates the original object.

### CODE REVIEW

**Comment by rofrischmann** [comment]
Hmm. Actually I never really thought about that much. I guess if you'd like to keep the original style object (I do not see any valid reason right now) you'd probably `Object.assign({}, style)` yourself before.
I think it might have performance issues if you're doing a lot of dynamic and periodic prefixing. Also I like that it's small and easy to understand as I wanted to keep this package as small and simple as possible, but of course I will think about that.

My suggestion might still be to just do:
```javascript
const prefixedStyle = prefixAll(Object.assign({}, style))

prefixedStyle !== style
```

**Comment by rtsao** [comment]
That makes sense.

The usage example makes it seem like it might return a new style object (rather than mutating the original), which caught me by surprise. To keep the original object, the user would need to make a deep copy, I think `Object.assign` won't work. But you're right, there doesn't seem to be a use case so I think that is fine.

I'll give this another go with a mutation in mind;  I can probably simplify the map/reduce logic.

**Comment by rofrischmann** [comment]
I thought Object.assign would actually really clone the object, but yeah one might use object-deep-assign I guess. I really appreciate your work here :)

**Comment by rtsao** [comment]
Closing in favor of: https://github.com/rofrischmann/inline-style-prefix-all/pull/16

**Pull request closed without merging**
